name: english_reader_backend
description: Simple REST backend for English Reader app
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  shelf: ^1.4.2
  shelf_router: ^1.1.3
  shelf_static: ^1.1.2
  uuid: ^4.4.0

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.8